name: Style Dictionary Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.json'

name: Style Dictionary Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.json'

name: Style Dictionary Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.json'

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan di sistem Ubuntu

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versi Node.js yang diinginkan

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install Style Dictionary
      - name: Install Style Dictionary
        run: npm install --save-dev style-dictionary

      # 5. Jalankan Style Dictionary build
      - name: Run Style Dictionary build
        run: npx style-dictionary build --config ./config.json

      # 6. Commit generated output
      - name: Commit generated output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/*  # Output di folder dist/
          git commit -m "Update generated files"

      # 7. Pull latest changes from remote (with rebase to avoid merge commits)
      - name: Pull latest changes from remote main branch (rebase)
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MIICollaboration/d-eS-D24Hzl8.git
          git pull origin main --rebase  # Mengambil perubahan dari remote dan rebase ke branch lokal

      # 8. Force Push to remote to overwrite conflicting changes
      - name: Force Push changes to remote
        run: |
          git push origin main --force  # Force push untuk mengatasi konflik

      - name: Debug Git Info
        run: |
          git remote -v
          git status
